import { chromium } from 'playwright';
import fs from 'node:fs/promises';
const BUILD = 'customer1-house-20260831a';
const BASE = 'http://127.0.0.1:8000';
const browser = await chromium.launch({ headless: true });
await fs.mkdir('qa-artifacts', { recursive: true });
async function assertNoHorizontalOverflow(page, label) {
  const geometry = await page.evaluate(() => {
    const client = document.documentElement.clientWidth;
    const offenders = [...document.querySelectorAll('body *')].map(el => { const rect=el.getBoundingClientRect(); const style=getComputedStyle(el); return {tag:el.tagName,id:el.id||'',cls:typeof el.className==='string'?el.className:'',left:Math.round(rect.left*10)/10,right:Math.round(rect.right*10)/10,width:Math.round(rect.width*10)/10,overflowX:style.overflowX,position:style.position,text:(el.textContent||'').trim().replace(/\s+/g,' ').slice(0,90)}; }).filter(x => x.right > client + 1 || x.left < -1).sort((a,b)=>Math.max(b.right-client,-b.left)-Math.max(a.right-client,-a.left)).slice(0,20);
    return {client,scroll:document.documentElement.scrollWidth,bodyClient:document.body.clientWidth,bodyScroll:document.body.scrollWidth,offenders};
  });
  if (geometry.scroll > geometry.client + 1 || geometry.bodyScroll > geometry.bodyClient + 1) {
    const isolation = await page.evaluate(() => { const measure=()=>document.documentElement.scrollWidth; const results={}; const selectors=['header','main','footer','.ticker','.hero-stage','.offer-stage','.house-proof','.identity-stage','.contact-routes','.service-hero','.service-body','.service-cta','.reading-progress','.hero-glow','.hero-monogram','.hero-seal','#house-field','.chapter-rail']; for(const selector of selectors){const nodes=[...document.querySelectorAll(selector)];const old=nodes.map(node=>node.getAttribute('style'));nodes.forEach(node=>node.style.setProperty('display','none','important'));results[`hide:${selector}`]=measure();nodes.forEach((node,index)=>old[index]===null?node.removeAttribute('style'):node.setAttribute('style',old[index]));} const pseudo=document.createElement('style');pseudo.textContent='*::before,*::after{display:none!important}';document.head.append(pseudo);results['no-pseudo']=measure();pseudo.remove();const motion=document.createElement('style');motion.textContent='*{animation:none!important;transform:none!important}';document.head.append(motion);results['no-animation-transform']=measure();motion.remove();return results; });
    throw new Error(`${label}: horizontal overflow ${JSON.stringify({...geometry,isolation})}`);
  }
}
async function assertBuild(page,label){const build=await page.locator('meta[name="hoc-build"]').getAttribute('content');if(build!==BUILD)throw new Error(`${label}: wrong build marker ${build}`);}
async function assertFocus(page,label){await page.keyboard.press('Tab');const focus=await page.evaluate(()=>{const el=document.activeElement;const style=getComputedStyle(el);const rect=el.getBoundingClientRect();return{tag:el?.tagName||'',outlineStyle:style.outlineStyle,outlineWidth:parseFloat(style.outlineWidth||'0'),visible:rect.width>0&&rect.height>0}});if(!focus.visible||focus.outlineStyle==='none'||focus.outlineWidth<2)throw new Error(`${label}: first keyboard focus is not strongly visible: ${JSON.stringify(focus)}`);}
async function assertExperience(page,name){for(const selector of ['#house-field','.motion-control','.chapter-rail','#work','#standard','#house','#contact'])if(!await page.locator(selector).count())throw new Error(`${name}: missing ${selector}`);const canvas=await page.locator('#house-field').evaluate(el=>({width:el.width,height:el.height}));if(canvas.width<1||canvas.height<1)throw new Error(`${name}: House field canvas not initialised`);await page.locator('.motion-control').click();if(await page.locator('.motion-control').getAttribute('aria-pressed')!=='true')throw new Error(`${name}: motion control did not pause`);if(!await page.getByRole('link',{name:/Website Release Assurance/i}).count())throw new Error(`${name}: current service is not discoverable`);}
async function exercise(viewport,name,options={}){const context=await browser.newContext({viewport,...options});const page=await context.newPage();const externalRequests=[];page.on('request',request=>{const url=new URL(request.url());if(url.hostname!=='127.0.0.1')externalRequests.push(request.url());});await page.goto(`${BASE}/index.html`,{waitUntil:'networkidle'});await assertBuild(page,`${name} home`);await page.locator('h1').waitFor({state:'visible'});await assertNoHorizontalOverflow(page,`${name} home`);await assertExperience(page,name);await assertFocus(page,`${name} home`);await page.screenshot({path:`qa-artifacts/${name}-home.png`,fullPage:true});for(const [path,title] of [['website-release-assurance.html','service'],['catalogue.html','house'],['privacy.html','privacy'],['terms.html','terms'],['404.html','404']]){await page.goto(`${BASE}/${path}`,{waitUntil:'networkidle'});await assertBuild(page,`${name} ${title}`);await page.locator('h1').waitFor({state:'visible'});await assertNoHorizontalOverflow(page,`${name} ${title}`);}await page.goto(`${BASE}/website-release-assurance.html`,{waitUntil:'networkidle'});if(!(await page.locator('body').textContent()).includes('£149'))throw new Error(`${name}: service price missing`);await page.goto(`${BASE}/index.html`,{waitUntil:'networkidle'});await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await assertNoHorizontalOverflow(page,`${name} 200% text`);if(!await page.locator('#contact').isVisible()||!await page.locator('#work').isVisible())throw new Error(`${name}: core content lost at 200% text`);await page.goto(`${BASE}/index.html?hocdiag=1`,{waitUntil:'networkidle'});const diagnostic=page.locator('#hoc-diagnostic-panel');await diagnostic.waitFor({state:'visible'});const diagText=await diagnostic.textContent();if(!diagText?.includes(BUILD)||!diagText.includes('CSS viewport')||!diagText.includes('Pointer coarse')||!diagText.includes('Reduced motion'))throw new Error(`${name}: diagnostic mode incomplete`);if(externalRequests.length)throw new Error(`${name}: unexpected external requests: ${[...new Set(externalRequests)].join(', ')}`);await context.close();}
await exercise({width:1440,height:900},'desktop');await exercise({width:390,height:844},'mobile');await exercise({width:320,height:900},'reflow-320');await exercise({width:800,height:1280},'wide-mobile',{hasTouch:true,isMobile:true,deviceScaleFactor:2});await exercise({width:1200,height:900},'wide-touch',{hasTouch:true,isMobile:true,deviceScaleFactor:1});
const reducedContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const reducedPage=await reducedContext.newPage();await reducedPage.goto(`${BASE}/index.html`,{waitUntil:'networkidle'});if(await reducedPage.evaluate(()=>document.documentElement.dataset.motion)!=='reduced')throw new Error('reduced-motion preference not honoured by interaction system');if(await reducedPage.locator('.motion-control').getAttribute('aria-pressed')!=='true')throw new Error('motion control does not reflect reduced-motion state');await reducedContext.close();
const noJsContext=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:false});const noJsPage=await noJsContext.newPage();await noJsPage.goto(`${BASE}/index.html`,{waitUntil:'load'});await assertNoHorizontalOverflow(noJsPage,'no-JS mobile');for(const selector of ['#work','#standard','#house','#contact'])if(!await noJsPage.locator(selector).isVisible())throw new Error(`no-JS: ${selector} missing`);await noJsContext.close();await browser.close();console.log('PASS: Customer 1 mature House render, service journey, responsive/text enlargement, reduced-motion, no-JS and diagnostics checks');
